# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

pod 'Firebase/Core'
pod 'Fabric', '~> 1.7.5'
pod 'Crashlytics', '~> 3.10.1'

target 'PanaceaReactNativeClient' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PanaceaReactNativeClient
  target 'PanaceaReactNativeClientTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'PanaceaReactNativeClient-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PanaceaReactNativeClient-tvOS

  target 'PanaceaReactNativeClient-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
