fastlane_version '2.53.1'

before_all do
  ensure_git_branch(
    branch: 'release'
  )
  ensure_git_status_clean
end

platform :ios do

  before_all do
    username = ENV["APPLE_ID"]
      cert(
        username: "#{username}"
      )
  end

  desc 'Increase build number and build new ios version available in archive section of xcode'
    lane :beta do
      team_id = CredentialsManager::AppfileConfig.try_fetch_value(:team_id)
      app_identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
      profile = ENV["sigh_#{app_identifier}_appstore"]
      sh "echo sigh_#{app_identifier}_appstore"
      increment_build_number(xcodeproj: './ios/PanaceaReactNativeClient.xcodeproj')
      gym(
        scheme: 'PanaceaReactNativeClient',
        xcargs: "PROVISIONING_PROFILE_SPECIFIER='#{profile}' DEVELOPMENT_TEAM='#{team_id}'",
        project: "ios/PanaceaReactNativeClient.xcodeproj"
      )
  end
end

platform :android do
  desc 'Build the Android application.'
  private_lane :build do
    gradle(task: 'clean', project_dir: 'android/')
    gradle(task: 'assemble', build_type: 'Release', project_dir: 'android/')
  end

  desc 'Ship to Playstore Beta.'
    lane :beta do
      build
      supply(track: 'beta', track_promote_to: 'beta')
      git_commit(path: ['./android/gradle.properties'], message: 'Bump versionCode')
      push_to_git_remote
    end
end
